# Generated by Django 3.2 on 2021-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('curso', models.CharField(choices=[], max_length=300, verbose_name='Curso')),
                ('status', models.CharField(choices=[('1', 'Não disponivel para os alunos'), ('2', 'Disponivel para os alunos'), ('3', 'Em correção')], max_length=300, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['id'],
            },
        ),
    ]
