# Generated by Django 3.2 on 2021-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[], max_length=300)),
                ('prova', models.CharField(choices=[], max_length=300)),
                ('numero', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('pergunta', models.TextField()),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['id'],
            },
        ),
    ]
